### ISSUE TITLE
Not working with version 1.3.2.1, also freezes my timer

### ISSUE THREAD

**Issue by luisfae** [Adventium-underscore/TEC-Autosplitter#2]
I'm running TEC on a Windows 10 machine, along with version 1.3.2.1 on Epic Games Launcher with the latest version of Livesplit.

I can download the autosplitter just fine, but it doesnt work for auto starting or anything. In fact, it freezes the timer. I think it is actually automatically resetting as soon as it starts, because sometimes I see the timer starting at 1 and then going back to 0.

I actually have to deactivate Autosplitter for the timer to even work. Any idea what can be done?

**Comment by Adventium-underscore** [comment]
I didn't know that EGS got a 1.3.2.1 patch since I never saw any patch notes from Enhance and Steam didn't get one and is still just 1.3.2. Since I have to update the autosplitter manually for every patch, that means that it's technically unsupported at the moment. Sorry about that.

I will update the autosplitter as soon as I can. However, I don't own the EGS version myself so I have to get a friend to help, so I can't say exactly when I can push the update. I'll make sure to leave another comment when I do.

**Comment by Adventium-underscore** [comment]
The reason your timer freezes is because the autosplitter does find the executable, but the memory addresses it reads are wrong. It's likely trying to read IGT and always getting a 0, so it keeps setting the timer to 0 because that's what it thinks the IGT is.

**Comment by Adventium-underscore** [comment]
Autosplitter has been updated to support 1.3.2.1
